runtime: nodejs
env: flex
manual_scaling:
  instances: 1
#resources:
#  cpu: .5
#  memory_gb: 0.18
#  disk_size_gb: 10

env_variables:
  SQL_USER: test
  SQL_PASSWORD: justtesting
  SQL_DATABASE: test
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: wallet-fox-ics:us-central1:googlecloud-walletfox-database
  beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: wallet-fox-ics:us-central1:googlecloud-walletfox-database